# This is a basic workflow to help you get started with Actions

name: Test execution and deploy to DEV

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v1
      
    - uses: yaananth/run-notebook@v1
      env:
        GSHEET_API_CREDENTIALS: ${{ secrets.GSHEET_API_CREDENTIALS }}
        GSHEET_KEY: 1ZILeAru7cNH0FOUwFQllWh2MlVsdBKSc3LyBLmZsi9o
      with:
        notebook: "JH_COVID-19.ipynb"
        isReport: False
    
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
